### ISSUE TITLE
[Question] Which UEFI version?

### ISSUE THREAD

**Issue by aaronrancsik** [almalmi/zbook-15-g1-hackintosh#4]
Is this created from the latest at this time 01.46 08/28/2019 UEFI version?

**Comment by almalmi** [comment]
You could use:
https://github.com/almalmi/EFI-Opencore-Hp-Zbook-15/releases/tag/0.6.0

**Comment by aaronrancsik** [comment]
Thank you, I will rebuild that to understand, but you just saved me so much time, thanks again.
